//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Accepted defines model for Accepted.
type Accepted struct {
	// Slot Example: A
	Slot string `json:"slot"`

	// Status Example: accepted
	Status string `json:"status"`
}

// ConfigDoc defines model for ConfigDoc.
type ConfigDoc struct {
	// Yaml The policy config as YAML text.
	Yaml string `json:"yaml"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// InsertRequest defines model for InsertRequest.
type InsertRequest struct {
	// Dir Directory to present as the card's contents. Defaults to <MOCK_FIXTURE_DIR>/<slot> when omitted.
	Dir *string `json:"dir,omitempty"`

	// Slot Reader slot identifier, e.g. "A".
	//
	// Example: A
	Slot string `json:"slot"`
}

// Job defines model for Job.
type Job struct {
	Bytes      *int64     `json:"bytes,omitempty"`
	Copied     *int       `json:"copied,omitempty"`
	Deduped    *int       `json:"deduped,omitempty"`
	Erased     *int       `json:"erased,omitempty"`
	Error      *string    `json:"error,omitempty"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         int64      `json:"id"`
	Serial     string     `json:"serial"`
	Skipped    *int       `json:"skipped,omitempty"`
	Slot       string     `json:"slot"`
	StartedAt  time.Time  `json:"startedAt"`

	// Status running | complete | error
	Status string `json:"status"`
}

// RemoveRequest defines model for RemoveRequest.
type RemoveRequest struct {
	// Slot Example: A
	Slot string `json:"slot"`
}

// SlotState defines model for SlotState.
type SlotState struct {
	JobId *int64 `json:"jobId,omitempty"`
	Slot  string `json:"slot"`

	// State idle | ingesting
	State string `json:"state"`
}

// Stats defines model for Stats.
type Stats struct {
	Bytes        int64 `json:"bytes"`
	CompleteJobs int   `json:"completeJobs"`
	ErrorJobs    int   `json:"errorJobs"`
	FilesCopied  int   `json:"filesCopied"`
	TotalJobs    int   `json:"totalJobs"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// GetJobsParams defines parameters for GetJobs.
type GetJobsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutConfigJSONRequestBody defines body for PutConfig for application/json ContentType.
type PutConfigJSONRequestBody = ConfigDoc

// DevInsertJSONRequestBody defines body for DevInsert for application/json ContentType.
type DevInsertJSONRequestBody = InsertRequest

// DevRemoveJSONRequestBody defines body for DevRemove for application/json ContentType.
type DevRemoveJSONRequestBody = RemoveRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetConfig Current policy config as YAML.
	// (GET /api/v1/config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// PutConfig Replace the policy config (validated before saving).
	// (PUT /api/v1/config)
	PutConfig(w http.ResponseWriter, r *http.Request)
	// DevInsert Simulate inserting a card (mock reader mode only).
	// (POST /api/v1/dev/insert)
	DevInsert(w http.ResponseWriter, r *http.Request)
	// DevRemove Simulate removing a card (mock reader mode only).
	// (POST /api/v1/dev/remove)
	DevRemove(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness probe.
	// (GET /api/v1/healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetJobs Recent ingest jobs, newest first.
	// (GET /api/v1/jobs)
	GetJobs(w http.ResponseWriter, r *http.Request, params GetJobsParams)
	// GetStats Aggregate ingest statistics.
	// (GET /api/v1/stats)
	GetStats(w http.ResponseWriter, r *http.Request)
	// GetStatus Live per-slot ingest state.
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutConfig operation middleware
func (siw *ServerInterfaceWrapper) PutConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DevInsert operation middleware
func (siw *ServerInterfaceWrapper) DevInsert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevInsert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DevRemove operation middleware
func (siw *ServerInterfaceWrapper) DevRemove(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevRemove(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobs operation middleware
func (siw *ServerInterfaceWrapper) GetJobs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/jobs", wrapper.GetJobs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/stats", wrapper.GetStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/config", wrapper.GetConfig)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/config", wrapper.PutConfig)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/dev/insert", wrapper.DevInsert)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/dev/remove", wrapper.DevRemove)

	return m
}

type BadRequestJSONResponse Error

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse ConfigDoc

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutConfigRequestObject struct {
	Body *PutConfigJSONRequestBody
}

type PutConfigResponseObject interface {
	VisitPutConfigResponse(w http.ResponseWriter) error
}

type PutConfig200JSONResponse ConfigDoc

func (response PutConfig200JSONResponse) VisitPutConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutConfig400JSONResponse struct{ BadRequestJSONResponse }

func (response PutConfig400JSONResponse) VisitPutConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsertRequestObject struct {
	Body *DevInsertJSONRequestBody
}

type DevInsertResponseObject interface {
	VisitDevInsertResponse(w http.ResponseWriter) error
}

type DevInsert202JSONResponse Accepted

func (response DevInsert202JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert400JSONResponse struct{ BadRequestJSONResponse }

func (response DevInsert400JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert409JSONResponse Error

func (response DevInsert409JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert501JSONResponse Error

func (response DevInsert501JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemoveRequestObject struct {
	Body *DevRemoveJSONRequestBody
}

type DevRemoveResponseObject interface {
	VisitDevRemoveResponse(w http.ResponseWriter) error
}

type DevRemove202JSONResponse Accepted

func (response DevRemove202JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove400JSONResponse struct{ BadRequestJSONResponse }

func (response DevRemove400JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove404JSONResponse Error

func (response DevRemove404JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove501JSONResponse Error

func (response DevRemove501JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobsRequestObject struct {
	Params GetJobsParams
}

type GetJobsResponseObject interface {
	VisitGetJobsResponse(w http.ResponseWriter) error
}

type GetJobs200JSONResponse []Job

func (response GetJobs200JSONResponse) VisitGetJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsRequestObject struct {
}

type GetStatsResponseObject interface {
	VisitGetStatsResponse(w http.ResponseWriter) error
}

type GetStats200JSONResponse Stats

func (response GetStats200JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200JSONResponse []SlotState

func (response GetStatus200JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetConfig Current policy config as YAML.
	// (GET /api/v1/config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// PutConfig Replace the policy config (validated before saving).
	// (PUT /api/v1/config)
	PutConfig(ctx context.Context, request PutConfigRequestObject) (PutConfigResponseObject, error)
	// DevInsert Simulate inserting a card (mock reader mode only).
	// (POST /api/v1/dev/insert)
	DevInsert(ctx context.Context, request DevInsertRequestObject) (DevInsertResponseObject, error)
	// DevRemove Simulate removing a card (mock reader mode only).
	// (POST /api/v1/dev/remove)
	DevRemove(ctx context.Context, request DevRemoveRequestObject) (DevRemoveResponseObject, error)
	// GetHealthz Liveness probe.
	// (GET /api/v1/healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetJobs Recent ingest jobs, newest first.
	// (GET /api/v1/jobs)
	GetJobs(ctx context.Context, request GetJobsRequestObject) (GetJobsResponseObject, error)
	// GetStats Aggregate ingest statistics.
	// (GET /api/v1/stats)
	GetStats(ctx context.Context, request GetStatsRequestObject) (GetStatsResponseObject, error)
	// GetStatus Live per-slot ingest state.
	// (GET /api/v1/status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutConfig operation middleware
func (sh *strictHandler) PutConfig(w http.ResponseWriter, r *http.Request) {
	var request PutConfigRequestObject

	var body PutConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutConfig(ctx, request.(PutConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutConfigResponseObject); ok {
		if err := validResponse.VisitPutConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DevInsert operation middleware
func (sh *strictHandler) DevInsert(w http.ResponseWriter, r *http.Request) {
	var request DevInsertRequestObject

	var body DevInsertJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevInsert(ctx, request.(DevInsertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevInsert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevInsertResponseObject); ok {
		if err := validResponse.VisitDevInsertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DevRemove operation middleware
func (sh *strictHandler) DevRemove(w http.ResponseWriter, r *http.Request) {
	var request DevRemoveRequestObject

	var body DevRemoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevRemove(ctx, request.(DevRemoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevRemove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevRemoveResponseObject); ok {
		if err := validResponse.VisitDevRemoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobs operation middleware
func (sh *strictHandler) GetJobs(w http.ResponseWriter, r *http.Request, params GetJobsParams) {
	var request GetJobsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobs(ctx, request.(GetJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobsResponseObject); ok {
		if err := validResponse.VisitGetJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStats operation middleware
func (sh *strictHandler) GetStats(w http.ResponseWriter, r *http.Request) {
	var request GetStatsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStats(ctx, request.(GetStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsResponseObject); ok {
		if err := validResponse.VisitGetStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhtb9s2EP4rB27AWsCVnb4MmId9cOO0TdeugZMBG5qiocWzfYlEquTJidf6vw8k/RJZcuKuTddPlkTq",
	"Xp577vTQH0Vq8sJo1OxE96Ow6AqjHYabp1IN8EOJjv1dajSjDpeyKDJKJZPR7XNntH/m0gnm0l/9aHEk",
	"uuKH9tp0O6669oG1xor5fN4SCl1qqfBGRFecTBBsdAZDo2ZwKR2QnsqMVCL8/oUJ76GXplgwKn9dWFOg",
	"ZYohu8yECPFK5kWGoit6oiV4VvhLx5b0WHhbLLl01Y1yabS2f94SPjSy3uPb5cut6OzdarsZnmPK3vy+",
	"0SMa901aD3Am88z/1rMvTEbpDNLwLkgHf/devwLGK05uDSlYbYok4l2LApePbzYbtzXZfYEy48nxCsaN",
	"KjTAay52BbbJ36F2aPkaG6sOFdk6qH2ymLKxM2ADhUWHmj2uPEFIpVU/OVhw2iXQx5EsM3Z+72nZ6TxK",
	"X7/Z//39s8O/Tv4cHLzvHw7CU2zHRV/6+AAuJ6jB5MSMKjnVjXRbsLIa3wClQgt+EUihZhoR2hZgMk7g",
	"VPROhS/8jUzeBHAbIV+aYR204YzjxcjYXLLoCtL88+O1F9KMY7TeQGoKiv1WX1OoymLbIlrptq81s7Al",
	"RqTJTVD1uBKfkowPmHJsApnUjrk4tCSzRr/ugoqtqSyr2DRNLH9esOsOqXLCllqTHsMn8MMzQ0b4BBGn",
	"24pPajmSVim2rs2qVYxN/Bhgbqa4tb12mqq7cvE4M+wHB9b9nJvh4c5VvKEa0XYVWVKZx5L0GB37rTsl",
	"sDTXmAhLdl/aVrHIL83Q3dAj25dHlKHbv6E52bDMtr2/kfF670Zk18Oo+mwt0q3j442THpl6JV6cnBxB",
	"7+gQRsauhnGsCxz32/vP8MpPa7eoFQS1IXWKCfSyDKwpGR1IizBF68hoVFBqP0rbsqD2dC+BkwnF4W5l",
	"ykBx5jtT2hTBjIBtyZNf4bmBidQqQ+tAagU+g2h4jBqtZFQwsiYHYrgknoCRBT1IjcIxarh3lsuL9daz",
	"+4vhTxw65FpSvaND0RKLYEVX7CWdpOOLYwrUsiDRFY+STvJItEQheRJKtUilHeWAfzLGwHdPtaC8fKeI",
	"58hRbIhWVbs97HS+mmhby5kG4RYXQZm0zFHzQquVeS7tzC+X1vrvbqO6STwIRdmQ11F5Pa8wlp4aNbur",
	"lNZdwLbE+f+F5bGcogqgPI4umyytQmtf0+dV0AdYZDLFwPoq8PeCoA7MHuLIWAQnp6TH92PdlqxTOG1T",
	"kFxhvhnXKF8KYzm2llpJrTNF9szXV4a2Xuku0nDmJ+pZAm90NgM5lZTJYbbQTyFSa1Lf9rbULvbb4KDX",
	"Pxi8f/2mf/BbbtKL2GFVpvRxGsXhHTGlqjx3YsvDr+Z8ddBpIEsMjIyG5cnlvzHHv/LLtzngRanrQGYW",
	"pZqBSdPSf0ZC4E86e3cfxR+GYamxSIMnFeRG4ebYOqa8zCQjxC7w2xeEvhfesVG7+1fB6GzW0D82aKrr",
	"/VMjbpRdd0Tcqqb7jogbApPZV6Dt429LW8wLnn3HXA2M+1yqTsJJ/p+bFMaLxZY7/CxW/k9o+jKinVKK",
	"vgplsQnAK5qi9l+OwpohVtM7X0jfbbktNG0hrcyR0TrRfftRkPf5oUQ7Ey2hZe4FXUY5hQPBKiEV/zMQ",
	"3SedlsjlFeVl7m/8Hel4t1eX/fN3XwgkMebuNkT9kX++ci6tlbMmYF+aIUzI+W93UlMRafxyBxHrgWyB",
	"xkt/MyLruAq0W56GtiEdj0t3yKHooIk8fmEzu954bHEcR3xI0CdAjil19cTKWzMrvzi1naq6PjzvUNul",
	"9g7zK5xjXVPrQIH2QZxxayRCG8U/S6bLrihtJrqiLebv5v8GAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
