//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Accepted defines model for Accepted.
type Accepted struct {
	// Slot Example: A
	Slot string `json:"slot"`

	// Status Example: accepted
	Status string `json:"status"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// InsertRequest defines model for InsertRequest.
type InsertRequest struct {
	// Dir Directory to present as the card's contents. Defaults to <MOCK_FIXTURE_DIR>/<slot> when omitted.
	Dir *string `json:"dir,omitempty"`

	// Slot Reader slot identifier, e.g. "A".
	//
	// Example: A
	Slot string `json:"slot"`
}

// RemoveRequest defines model for RemoveRequest.
type RemoveRequest struct {
	// Slot Example: A
	Slot string `json:"slot"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// DevInsertJSONRequestBody defines body for DevInsert for application/json ContentType.
type DevInsertJSONRequestBody = InsertRequest

// DevRemoveJSONRequestBody defines body for DevRemove for application/json ContentType.
type DevRemoveJSONRequestBody = RemoveRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// DevInsert Simulate inserting a card (mock reader mode only).
	// (POST /api/v1/dev/insert)
	DevInsert(w http.ResponseWriter, r *http.Request)
	// DevRemove Simulate removing a card (mock reader mode only).
	// (POST /api/v1/dev/remove)
	DevRemove(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness probe.
	// (GET /api/v1/healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DevInsert operation middleware
func (siw *ServerInterfaceWrapper) DevInsert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevInsert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DevRemove operation middleware
func (siw *ServerInterfaceWrapper) DevRemove(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevRemove(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/dev/insert", wrapper.DevInsert)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/dev/remove", wrapper.DevRemove)

	return m
}

type BadRequestJSONResponse Error

type DevInsertRequestObject struct {
	Body *DevInsertJSONRequestBody
}

type DevInsertResponseObject interface {
	VisitDevInsertResponse(w http.ResponseWriter) error
}

type DevInsert202JSONResponse Accepted

func (response DevInsert202JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert400JSONResponse struct{ BadRequestJSONResponse }

func (response DevInsert400JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert409JSONResponse Error

func (response DevInsert409JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DevInsert501JSONResponse Error

func (response DevInsert501JSONResponse) VisitDevInsertResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemoveRequestObject struct {
	Body *DevRemoveJSONRequestBody
}

type DevRemoveResponseObject interface {
	VisitDevRemoveResponse(w http.ResponseWriter) error
}

type DevRemove202JSONResponse Accepted

func (response DevRemove202JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove400JSONResponse struct{ BadRequestJSONResponse }

func (response DevRemove400JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove404JSONResponse Error

func (response DevRemove404JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DevRemove501JSONResponse Error

func (response DevRemove501JSONResponse) VisitDevRemoveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// DevInsert Simulate inserting a card (mock reader mode only).
	// (POST /api/v1/dev/insert)
	DevInsert(ctx context.Context, request DevInsertRequestObject) (DevInsertResponseObject, error)
	// DevRemove Simulate removing a card (mock reader mode only).
	// (POST /api/v1/dev/remove)
	DevRemove(ctx context.Context, request DevRemoveRequestObject) (DevRemoveResponseObject, error)
	// GetHealthz Liveness probe.
	// (GET /api/v1/healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DevInsert operation middleware
func (sh *strictHandler) DevInsert(w http.ResponseWriter, r *http.Request) {
	var request DevInsertRequestObject

	var body DevInsertJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevInsert(ctx, request.(DevInsertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevInsert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevInsertResponseObject); ok {
		if err := validResponse.VisitDevInsertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DevRemove operation middleware
func (sh *strictHandler) DevRemove(w http.ResponseWriter, r *http.Request) {
	var request DevRemoveRequestObject

	var body DevRemoveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevRemove(ctx, request.(DevRemoveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevRemove")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevRemoveResponseObject); ok {
		if err := validResponse.VisitDevRemoveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zJZvb9s2E8C/yoHPA6wFPMlpuhfzsBdunTbG1iVwMmBAU8QMebbYSCR3pJx6gb/7cKTi2rFTZEBa9B1F",
	"Hu/v7466Fco13lm0MYjBrSAM3tmA6eOV1BP8u8UQ+Us5G9GmpfS+NkpG42z5MTjLe0FV2Ehe/Z9wJgbi",
	"f+Vn1WU+DeURkSOxWq16QmNQZDwrEQNxXiFQNgZXTi/hRgYwdiFrowvB8p0KtjBUCn1EzWtPziNFk10O",
	"tUse4ifZ+BrFQAxFT8Sl52WIZOxcsK4oYxu2BeWd0h35VU+wa4bY4vu7y71s7MNa3F19RBVZfY5yxzm8",
	"2/6y/iy2T+8xyjpWZ2vn78W+Jyh3/dhw9tkb24AUNxjYNqhNima7kCNDqKKjJUQHnjCgjSADxApBSdI/",
	"BOhICgWMcCbbOgaWvWj7/UP17uT1b5dvxn+d/zk5uhyNJ2kXy3zICc8bcFOhBdeYGFEXF3ZvkTsWtv2b",
	"oNRIwIdgNNpoZgapB1jMC7gQwwtRiN6X+bmfwIcwmGDjFvhg+h7F6uNssZixM7cb7vH5+SkMT8cwc7Su",
	"gbFz7rOzUfn6DX7iInGvpb3U2tIqLGBY10CujRhAEsICKRhnUUNrOYOl9KZcHBRwXplcU5IqgsmlDq4l",
	"heBmEKmN1S/w1kElra6RAkirgSPIiudokWREDTNyDZgINyZW4KQ3PyqncY4Wnk0bef1ZdPq8q7mJKXEb",
	"QQ1Px6InOmfFQBwU/aLP1XAerfRGDMRh0S8ORU94GatUiS6UUuOiNIn5VC0X9vLjHcUcpF6zPtWGpoy5",
	"TAleg28sTLlm0wJObL0EuZCmlld1BzAr8eQUF4BaG3Lkk6Ph6Ghy+e5kdPRr49R1jpXRSSN3rLnNcJG7",
	"U2RAMMRXTi+fbFBvt/5qm8NILaaNjcfiRf/Fkxlfz/c9D0V2zDgLdwO74Oq+7Pcf0rp2s9x40NKVn7/N",
	"u5ZnTQBZE0q9BKdU603n+E/9g6/vxR8uMl/W2DkjyVBB4zR2L2vbNJKWYiDOTNPWMiLkLmDxDuhn6Q7l",
	"4clXwdl6+Twr2OwfSkNvs392wM1z8SuBuz10vyNwk2OyfgJsX35bbLHxcfkds5qI+6+oVulX6h/2co57",
	"MH2L8bgT2eGl/2RJ2Pqh25OLM6SFUchVaP39BPxuFmj55fDkrlJ6+BiJ3z4xeH8rWqrFQJRi9WH1bwAA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
